# Generated by Django 4.2.1 on 2023-11-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetForm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formtemplate',
            name='field_name_1',
        ),
        migrations.RemoveField(
            model_name='formtemplate',
            name='field_name_2',
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='fields',
            field=models.JSONField(default='qwerty'),
            preserve_default=False,
        ),
    ]
